version: '3.2'

services:
  app:
    image: nginx:1.13-alpine
    ports:
      - 8001:80/tcp
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./public:/var/www/uw/src/public
    depends_on:
      - users-php
    networks:
      - uw-internal-1
      - users-1
    container_name: users_app

  users-php:
    image: uw-php
    volumes:
      - ./public:/var/www/uw/src/public
      - ./vendor:/var/www/uw/vendor
    ports:
      - 9000
    depends_on:
      - redis
    networks:
      - uw-internal-1
      - users-1

  redis:
    image: redis:4.0.2
    networks:
      - users-1

networks:
    uw-internal-1:
      external: true
    users-1:
